### ISSUE TITLE
Query regarding timestep 

### ISSUE THREAD

**Issue by utkarshp1161** [davkovacs/BOTNet-datasets#1]
Can you please let me know the time step used for simulating the data here? Thanks

**Comment by davkovacs** [comment]
Can you please elaborate what exactly you mean?

**Comment by utkarshp1161** [comment]
as per your colab tutorial in mace  repository the forward simulation part is:

from ase import units
from ase.md.langevin import Langevin
from ase.io import read, write
import numpy as np
import time

from mace.calculators import MACECalculator

calculator = MACECalculator(model_path='/content/checkpoints/MACE_model_run-123.model', device='cuda')
init_conf = read('BOTNet-datasets/dataset_3BPA/test_300K.xyz', '0')
init_conf.set_calculator(calculator)

dyn = Langevin(init_conf, 0.5*units.fs, temperature_K=310, friction=5e-3)
def write_frame():
        dyn.atoms.write('md_3bpa.xyz', append=True)
dyn.attach(write_frame, interval=50)
dyn.run(100)
print("MD finished!")

-------------------

I have trained a ml potential on your acac data. I want to compare the forward simulation model with the test set of acac data. I would need  "Langevin(init_conf, time_step, temperature_K= temp, friction= friction)" to run the simulation. What time step shall I put so I am consistent with the ground truth data?

**Comment by davkovacs** [comment]
The test set is best used by comparing it as single point evaluations. I do not recommend trying to reproduce the MD trajectory. Simply evaluate with your model the data points and compare to the given DFT energies and forces.

**Comment by utkarshp1161** [comment]
Thank you for your suggestion; I see your point and will add this to my evaluation startergy. For now, I have trained different gnn models on this data and want to compare how they perform over trajectory (rollout error). I just wanted to try this out. Would you recommend any specific time step? like 0.5 fs for the 3bpa above?

**Comment by davkovacs** [comment]
It depends on the temperature. At room temperature you should be able to use 1 fs.

**Comment by utkarshp1161** [comment]
Thank you. How about the 600K one?

**Comment by davkovacs** [comment]
At higher temperature use 0.5 fs.

**Comment by utkarshp1161** [comment]
Thank you.
